name: Python Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
          sudo apt-get install -y portaudio19-dev
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

    - name: Run tests
      run: |
          pip install pytest pytest-cov
          pytest tests/tests.py --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
      if: ${{ always() }}
